apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coroot-operator
  namespace: argocd
spec:
  tenplate:
    metadata:
      name: coroot-operator
    spec:
      project:  o11y
      source:
        repoURL: https://coroot.github.io/helm-charts
        targetRevision: 0.15.15
        chart: coroot-operator
        helm:
          releaseName: prometheus
          values: |
            corootCE:
              replicas: 2
              existingPrometheus:
                enabled: true
                service:
                  serviceName: prometheus
    destination:
      server: https://kubernetes.default.svc
      namespace: o11y
    syncPolicy:
        automated:
          prune: true
          selfHeal: true
          serverSideApply: true
        syncOptions:
        - CreateNamespace=true