apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  project: monitoring
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 'HEAD' 
         # Not good pratice to point to a branch, treats the CRD as a mutable resource
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus
          # Override the default values for the prometheus chart
          # using `values: |` is considered an anti-pattern, as it mixes ArgoCD manifest 
          # and Helm manifest
          # A better approach is to have the values load from a dependency chart .
      valueFiles:
      - $values/charts/prometheus/values-dev.yaml
  - repoURL: 'https://github.com/marcpires/charts.git'
    targetRevision: 'chore/initial-charts'
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  syncOptions:
    - CreateNamespace=true
