apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: "in-cluster"
  template:
    metadata:
      name: prometheus
    spec:
      project: monitoring
      source:
       - repoURL: https://prometheus-community.github.io/helm-charts
         targetRevision: 65.8.0
         chart: kube-prometheus-stack
         helm:
          releaseName: prometheus
          # Override the default values for the prometheus chart
          # using values: | is an anti-pattern, as it mixes ArgoCD maniufest and Helm
          # this instead adds a separaration of concerns.
          valueFiles:
          - $values/charts/prometheus/values.yaml
       - repoURL: 'https://gitub.com/marcpires/charts.git'
         targetRevision: 65.8.0
         ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
