apiVersion: argocdproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argocdproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - cluster: "in-cluster"
  template:
    metadata:
      name: sealed-secrets
    spec:
      project: infra
      source:
        - repoURL:  https://bitnami-labs.github.io/sealed-secrets
          targetRevision: HEAD
          chart: sealed-secrets
          helm:
            releaseName: sealed-secrets
            valuesFiles:
            - $values/charts/sealed-secrets/values.yaml
        - repoURL: https://github.com/marcpiresrj/charts.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true 
